alias ls='lsd'
alias la='lsd -a'
alias ll='ls -la'
alias cat='bat'
#alias nvim='emacs -nw'
alias doom='emacs -nw'
alias gedit='gnome-text-editor'
alias grep='grep --color=auto'
alias sudonautilus='nautilus admin:///'
